---
title: "Year One in Review"
description: |
  A reflection on my first year (and change) in the real world. 
preview: preview.png
author:
  - name: Jason Bixon
    url: https://jasonbixonblog.netlify.com
    affiliation: Merkle Inc.
    affiliation_url: https://merkleinc.com
date: 08-04-2019
repository_url: https://github.com/jbixon13/Radix-blog
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Thinking back to last summer and how my professional competency has changed feels like thinking back to a completely different person. 

I graduated Penn State with about as much technical literacy as I could fit into a business degree. I specialized in marketing analytics, worked as a research assistant in a psychology lab, and interned as a data analyst at a global ad agency, but even so I don't feel I was prepared for the modern analytical toolset used outside of academia. I was taught tools like SPSS and Excel; any programming experience came from seeking it out myself, which led to scattershot attempts to learn through workshops without a true incentive or application.

When I interviewed for my first full-time data analyst positions I was comfortable with statistical thinking and visualization, but had no technical experience with tools like R or Python. I was lucky enough to get hired and learned very quickly that it's extremely unreasonable to learn programming without a destination in mind. I learned quicker than my previous attempts because I could learn one error at a time to reach the destination of a finished analysis that was well-defined from its inception. 

I taught myself R and SAS simultaneously which I would not recommend; what sustained my growth the most was committing myself to learn one new concept in every project I took on. One of my biggest frustrations with R in the past was just setting up my working directory properly to read files in. The first thing I learned was as simple as using projects within R Studio to avoid unnecesary directory assignment. It was simple, but every little victory allowed me to be greater than the sum of those victories. I was learning not just new skills, but how to **learn programming itself.** Where to search for answers, what phrases to use to look for certain concepts, what examples I should aspire to emulate. This allowed for exponential improvement to my work and my confidence in it. 

I continue to find roadblocks in the projects I take on and continue this philosophy to tackle them. I don't expect that to change; this is a field for lifelong learners. I remain confident by reflecting on the kinds of challenges I face now vs. a year ago. Last year I struggled with simple data processing techniques: joining, summarizing, & filtering. Now I must carefully plan complex subqueries and their mechanics within large and messy tables. Last year I was excited and inspired to share methodology documentation in Rmarkdown. Now I am excited to deploy an enterprise Shiny application I developed to automate NLP techniques on open-ended survey responses. I would never have even dreamed of having the frustrations I have today.      

I still have a lot to learn and there is much I have left out of this quick summary of the last year. If I must focus on one thing it should be a reflection of my learning journey. Learning programming is more about mental stamina than anything. There will always be someone who "just gets it" and makes everything you've struggled with seem trivial. With enough stamina that can be how you from a year ago would feel about you today.