---
title: "New Year, New (First) Blog"
description: |
  Trying my best.
preview: preview.jpg
base_url: https://jasonbixon.netlify.com
author:
  - name: Jason Bixon
    url: https://jbixon13.wixsite.com/website
    affiliation: Merkle Inc.
    affiliation_url: https://merkleinc.com
date: 01-24-2019
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Now that I've spent an unfortunate amount of time debating the best way to share my work on the internet, I guess I should write about it a little. If anything maybe it will make me feel like it was worth it. 

I've never maintained a blog before (excluding the website me and my neighbor made when we were 8 where we gave completely inaccurate advice on pet ownership to people who are unquestionably worse off due to it) and I can't promise that I'll maintain this one either. 

I listen to the [**DataFramed Podcast**](https://www.datacamp.com/community/podcast) a lot and a piece of advice that is invariably given by data science experts is to maintain a blog where you share your work publically. That doesn't make it feel any less silly to share my work into the void that this will likely be, but if anything it will be a good way to practice hosting projects on the internet. 

Working with modern web frameworks is not exactly my forte, and I would probably continue actively avoiding anything even close to web development if that were possible. That being said, I am aware of how much more impactful data can be when it's interactive and painfully aware of [**how little I know about it.**](http://d3js.org) Thankfully, I can achieve a healthy dose of interactivity without having to learn JavaScript through packages like [**HTMLwidgets**](http://www.htmlwidgets.org/), [**Leaflet**](https://rstudio.github.io/leaflet/), [**plot.ly**](https://plot.ly/r/), and others. That allows me to spend more time working on the applied research questions I want to investigate and less time figuring out how to share them. 

The takeaway should not be that you can avoid learning how web frameworks work, as I know I will need to learn them eventually if I want to take my analyses to the point that I envision them in my head. My point is that as someone new to "data science" and programming in general, the R ecosystem has made my life inexpressibly less stressful due to its integration with modern tools for sharing my work.